name: Run Tests and Merge to Staging

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --tb=short --disable-warnings

    - name: Merge develop into staging
      if: success()
      run: |
        git fetch --all
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout staging
        git merge develop
        git push origin staging
